(package "pkm"
         "0.0.1"
         "Personal Knowledge Manager")

(website-url "https://github.com/jinder1s/pkm.git")
(keywords "notes" "tasks" "habits" "clocks")

(package-file "pkm.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "29.0")
(depends-on "dash" "2.13")
(depends-on "ts" "0.3")
(depends-on "persist" "0.5")


(development
  (depends-on "undercover"))

(files "*.el")
